config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'welcome/index'

  resources :gates do
  	resources :keys
  end

  root 'gates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	belongs_to :gate
end

app/models/gate.rb
class Gate < ApplicationRecord
	#has_one :area

	has_many :keys, dependent: :destroy
	validates :codigo, presence: true,
                    length: { minimum: 1 }

end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to :gate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gates_controller.rb
class GatesController < ApplicationController
  
  http_basic_authenticate_with name: "neko", password: "123", except: [:index, :show]

  def index
  	@gates = Gate.all
  end

  def show
    @gate = Gate.find(params[:id])
  end

  def new
  	@gate = Gate.new
  end

  def edit
  @gate = Gate.find(params[:id])
  end

  def create
	@gate = Gate.new(gate_params)

	if @gate.save
       redirect_to @gate
    else
       render 'new'
    end
  end

  def update
  @gate = Gate.find(params[:id])
 
  if @gate.update(gate_params)
    redirect_to @gate
  else
    render 'edit'
  end
end


def destroy
  @gate = Gate.find(params[:id])
  @gate.destroy
 
  redirect_to gates_path
end

  private
	def gate_params
    params.required(:gate).permit(:codigo, :ubicacion, :descripcion, :area)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController

def create
    @gate = Gate.find(params[:gate_id])
    @key = @gate.keys.create(key_params)
    redirect_to gate_path(@gate)
  end

  def destroy
    @gate = Gate.find(params[:gate_id])
    @key = @gate.keys.find(params[:id])
    @key.destroy
    redirect_to gate_path(@gate)
  end
 
  private
    def key_params
      params.require(:key).permit(:codigo, :numero_de_copia)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gates/_form.html.erb
<div class="container"> 

  <%= form_with model: @gate, local: true do |form| %>
 
  <% if @gate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gate.errors.count, "error") %>, no se puede guardar esta puerta:
      </h2>
      <ul>
        <% @gate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <div class="form-group">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, :class => "form-control", placeholder: "Número" %>
  </div>
 
  <div class="form-group">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion, :class => "form-control", placeholder: "..." %> 
  </div>

  <div class="form-group">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, :class => "form-control", placeholder: "Observaciones" %>
  </div>


  <h4>Área</h4>
  <div class="checkbox">
  <% Area.all.each do |rt| %>
    <%= form.radio_button :area, rt.descripcion %>
    <%= form.label :area, rt.descripcion %>

  <% end %>
  </div>


  <div class="form-group">
    <%= form.submit :class=> "btn btn-default"%>
  </div>
</div>

   
 
<% end %>

app/views/gates/edit.html.erb
<h1>Editar Puerta</h1>
 
<%= render 'form' %>
<%= link_to 'Ver LLaves', gate_path(@gate), :class=> "btn btn-default" %> 
<%= link_to 'Volver', gates_path %>

app/views/gates/index.html.erb
<h1>Lista de Puertas</h1>

<%= link_to 'Nueva Puerta', new_gate_path, class: 'btn btn-primary btn-lg' %>
 
<table class="table table-striped">
  <tr>
    <th>Codigo</th>
    <th>Ubicacion</th>
    <th>Descripcion</th>
    <th>Area</th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
 
  <% @gates.each do |gate| %>
    <tr>
      <td><%= gate.codigo %></td>
      <td><%= gate.ubicacion %></td>
      <td><%= gate.descripcion %></td>
      <td><%= gate.area %></td>
      <td><%= link_to 'Mostrar', gate_path(gate) %></td>
      <td><%= link_to 'Editar', edit_gate_path(gate) %></td>
       <td><%= link_to 'Eliminar', gate_path(gate),
              method: :delete,
              data: { confirm: '¿Estas seguro?' } %></td>
    </tr>
  <% end %>
</table>

app/views/gates/new.html.erb
<h1>Nueva Puerta</h1>

<%= render 'form' %>

<%= link_to 'Volver', gates_path %>

app/views/gates/show.html.erb
<p>
  <strong>Codigo:</strong>
  <%= @gate.codigo %>
</p>
 
<p>
  <strong>Ubicacion:</strong>
  <%= @gate.ubicacion %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @gate.descripcion %>
</p>

<p>
  <strong>Area:</strong>
  <%= @gate.area %>
</p>


<h2>Llaves</h2>
<%= render @gate.keys %>

<h2>Agregar Llave</h2>
<%= render 'keys/form' %>

<%= link_to 'Editar', edit_gate_path(@gate) %> |
<%= link_to 'Volver', gates_path %>

app/views/home/index.html.erb
<h1 class="text-center text-muted">Hello bootstrap</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/keys/_form.html.erb
<%= form_with(model: [ @gate, @gate.keys.build ]) do |form| %>

  <p>
    <%= form.label :codigo %><br>
    <%= form.text_field :codigo %>
  </p>
  <p>
    <%= form.label :numero_de_copia %><br>
    <%= form.text_field :numero_de_copia %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/keys/_key.html.erb
<p>
  <strong>Codigo:</strong>
  <%= key.codigo %>
</p>
 
<p>
  <strong>Numero de Copia:</strong>
  <%= key.numero_de_copia %>
</p>

<p>
  <%= link_to 'Eliminar Llave', [key.gate, key],
               method: :delete,
               data: { confirm: '¿Estas seguro?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doors</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#puertas</h1>

<%= link_to 'Gates', controller: 'gates' %>